export const FETCH_COUNTRY="FETCH_COUNTRY";
export const FETCH_COUNTRY_SUCCESS="FETCH_COUNTRY_SUCCESS";
export const FETCH_COUNTRY_ERROR="FETCH_COUNTRY_ERROR";


export const GET_COUNTRY="GET_COUNTRY";
export const GET_COUNTRY_SUCCESS="GET_COUNTRY_SUCCESS";
export const GET_COUNTRY_ERROR="GET_COUNTRY_ERROR";

export const FETCH_BORDER_COUNTRY="FETCH_BORDER_COUNTRY";
export const FETCH_BORDER_COUNTRY_SUCCESS="FETCH_BORDER_COUNTRY_SUCCESS";
export const FETCH_BORDER_COUNTRY_ERROR="FETCH_BORDER_COUNTRY_ERROR";